name: Build API Server Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Compile code to plain js
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compiling...
      run: cd api && npm i && npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: api-server
        path: api/build/


  api-image:
    permissions: write-all
    name: Build and Push API docker image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name:  api-server
        path:  api/build/
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build the Docker image
      run: docker compose -f ./api/docker/production/docker-compose.yml build
    - name: Push to GHCR.io
      run: docker push ghcr.io/apollo-xiv/k8s-api:latest